### PR TITLE
update version to 2.18.0.0

### PR DESCRIPTION
**Pull request by riddell-stan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

re: checklist. I don't use anaconda so I'm not familiar with re-rendering.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I think we need to update Windows compilation to use MingW-w64 toolchain.

So somewhere it should call `conda install libpython m2w64-toolchain -c msys2`. That should be enough.

**Comment by riddell-stan** [comment]
Where precisely should it go? What line?

Alternatively, if you'd like to submit a PR, I'll close this one.

**Comment by ahartikainen** [comment]
From `recipe/meta.yml`

```
build:
  number: 1
  skip: True  # [win and py27]
  detect_binary_files_with_prefix: False
```

can remove the skip statement.

#################

Maybe we can add `m2w64-toolchain` and `libpython` for `bld.bat`?

    conda install libpython m2w64-toolchain -c msys2

#################

**Comment by ahartikainen** [comment]
Yes.

**Comment by riddell-stan** [comment]
OK. I removed the customizations. Still not sure how to indicate that windows binaries should not be generated.

**Comment by rmax** [comment]
To skip windows builds add under `build` section:
```
  skip: True  # [win]
```

And I think you need to regenerate the feedstock via `conda smithy regenerate`. Make sure to upgrade `conda-smithy` to the latest version.

**Comment by riddell-stan** [comment]
@conda-forge-admin, please rerender

**Comment by riddella** [comment]
#13 looks better. I'll close this.

**Pull request closed without merging**
