### PR TITLE
PyStan 2.19.0.0

### PR DESCRIPTION
**Pull request by riddell-stan**
Checklist
* [x ] Used a fork of the feedstock to propose changes
* [x ] Bumped the build number (if the version is unchanged)
* [x ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by riddell-stan** [comment]
@conda-forge-admin, please rerender

**Comment by madjokal** [comment]
Are there any updates for this version?

**Comment by riddell-stan** [comment]
I think this is ready to publish. (Do we need to disable the failing Windows tests?)

**Comment by beckermr** [comment]
We should remove them only as a last resort. Is anyone in @conda-forge/pystan familiar with building on windows? I am not.

**Comment by ahartikainen** [comment]
I think it should be build against `mingw-w64` (`m2w64-toolchain` from conda-forge).

https://anaconda.org/conda-forge/m2w64-toolchain_win-64

**Comment by beckermr** [comment]
go for a PR @ahartikainen !

**Comment by beckermr** [comment]
This needs to be rebased on master or more easily, we should open a new PR.

**Pull request closed without merging**
