### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by hmaarrfk**
closes #14 

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
To upgrade to 2.18.0.0 I suggest merging the changes from defaults.

It seems that defaults includes:
```
  run:
    - {{ pin_compatible('numpy') }}
    # http://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - libpython              # [win]
    - m2w64-toolchain        # [win]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
```

**Comment by beckermr** [comment]
Yes, the compilers need to be in the run section. I have used pystan extensively and you absolutely need to have a compiler to even use the package.

**Comment by beckermr** [comment]
Good question. I don’t think stan alone needs c but I wonder if the c++ compilers themselves need the c compiler to run. 

I’d follow defaults on this and include the c compiler under the assumption that there was a reason we don’t know of.

**Comment by beckermr** [comment]
Ack. Clearly the c++ compilers don’t need the c ones since the tests did run, but matching defaults is probably a good idea anyways.

**Comment by beckermr** [comment]
I do wonder if we want to remove the specific windows selector in the run section and let the conda forge config work out the right windows compiler. My experience on windows is non-existent so I have no idea.

**Comment by hmaarrfk** [comment]
I was going to say something about the windows one. My feeling is that this m2 stuff is work from @mingwandroid and probably the right move for windows for pystan. 

Since these programs are likely not be run outside of a higher level language. It should be OK in terms of user compatibility. That said, it does require a `toolchain` compiler, which would indicate that the user would have to install the m2 compiler themselves. I say let somebody raise an issue for it.

**Comment by beckermr** [comment]
I guess from the comment gcc is better hence the specific pin.

**Comment by beckermr** [comment]
I agree. Let's merge matching defaults and then see what happens...

**Comment by ahartikainen** [comment]
Stan codebase is not currently compatible with msvc, hence the mingw-w64.

Stan itself doesn't need C-compiler, but there are some C-packages that are not compiled by default (Sundials).

Stan can be compiled with clang + msvc libs but distutils is not updated yet to support this.

In runtime, pystan translates Stan code to C++ code, which is compiled to a python module with Cython. After compilation, module is imported to python and sampling is runned with this new compiled model.

**Comment by hmaarrfk** [comment]
Got it, thanks!

Yeah, I have a feeling these tests will pass

I remember there was somethign that stopped me from upgrading to 2.18

I guess that can be worked on after this. I just wanted to move this feedstock along.

**Comment by ahartikainen** [comment]
Probably C++11 that came with 2.18

**Comment by ahartikainen** [comment]
Yeah, but msvc fails with C++ templates using Eigen (at least with the templates used in Stan math)

**Comment by hmaarrfk** [comment]
Even 2017?

**Comment by ahartikainen** [comment]
You can try. I think that template bug has been problem all ready in 2008 (or something similar)

For clang-cl stuff here is an example https://github.com/ahartikainen/pystan_windows_threading

**Comment by beckermr** [comment]
Woooo! Let’s merge!

**Comment by beckermr** [comment]
Not mine either!

**Comment by beckermr** [comment]
@conda-forge/pystan

**Comment by ahartikainen** [comment]
I think @rmax can merge on this repo

**Comment by hmaarrfk** [comment]
Do any of you two have interested on being added as maintainers?

**Comment by beckermr** [comment]
Sure why not!

**Pull request merged**
