### PR TITLE
Update version to 2.17.1.0

### PR DESCRIPTION
**Pull request by ariddell**

### CODE REVIEW

**Comment by ahartikainen** [comment]
Change shanum256 to 

    d4f91b5300c002448c4141abb806264f929fffed4fb72b9dbdfd2def83529b78

got it for the source here: https://pypi.org/project/pystan/#files

**Comment by ariddell** [comment]
Thanks. Not sure where I got that sha256sum.

**Comment by rmax** [comment]
@conda-forge-admin, please rerender

Let's see if a rerender fixes the issue in the win build.

**Comment by ariddell** [comment]
If it previously passed on macOS perhaps this could be merged without waiting for travis?

**Comment by rmax** [comment]
Let's keep an eye on the master's travis build: https://travis-ci.org/conda-forge/pystan-feedstock/builds/331980827

**Comment by rmax** [comment]
For the record, the build finished successfully 2 days ago.

**Pull request merged**
