### PR TITLE
v2.19.0.0

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Well ok. I guess the new compilers didn't do it for v2.19. @ahartikainen Can you look at this?

**Comment by ahartikainen** [comment]
That is a bit weird. 
It installs m2w64 the same way in both PR, but this latest is still trying to build against MSVC.

I noticed, that even in my earlier PR `rd` command failed, but it was not important.

    rd /q /s doc doxygen make test lib\\cpplist_* lib\\gtest_*

Latest pystan has these lines to remove long paths

```
  - SETLOCAL ENABLEDELAYEDEXPANSION
  - FOR /D /R "pystan/stan/lib/stan_math/lib" %%D IN (doc) DO @IF EXIST "%%D" RD /S /Q "%%D"
  - FOR /D /R "pystan/stan/lib/stan_math/lib" %%D IN (test) DO @IF EXIST "%%D" RD /S /Q "%%D"
```

And I guess other paths / dirs could be deleted the same way (or changing `%%D IN (txtvalue)` --> `txtvalue IN (%%D)`

So the original error:

Should we also add `libpython` for build and other

```
requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - python
    - setuptools
    - numpy
    - cython >=0.22,!=0.25.1
  run:
    # http://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - python
    - {{ pin_compatible('numpy') }}
    - cython >=0.22,!=0.25.1
    - matplotlib
```

to 

```
requirements:
  build:
    - posix  # [win]
    - libpython  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - posix  # [win]
    - libpython  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - python
    - setuptools
    - numpy
    - cython >=0.22,!=0.25.1
  run:
    # http://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - posix  # [win]
    - libpython  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - python
    - {{ pin_compatible('numpy') }}
    - cython >=0.22,!=0.25.1
    - matplotlib
```

Also, arviz is now in conda-forge, so can it be added to be installed with the pystan from conda?

**Comment by beckermr** [comment]
I believe the pr allows edits from maintainers. I’ll try to get to this but feel free to go ahead otherwise

**Comment by ahartikainen** [comment]
I'm not a maintainer on conda-forge, or at least I think I'm not.

**Comment by beckermr** [comment]
I mean on this feedstock.

**Comment by ahartikainen** [comment]
Yes, I meant on this feedstock. I'm maintainer on ArviZ feedstock only.

**Comment by beckermr** [comment]
Well adding libpython did not help.

**Comment by beckermr** [comment]
@conda-forge/staged-recipes Can anybody with experience building on windows help us out here?

**Comment by ahartikainen** [comment]
I think libpython fails now. That is bizarre.

**Comment by ahartikainen** [comment]
Nice thing about this is that I have sometimes had these errors on my local machine too, and I have been unable to reproduce these.

So there is something weird with `libpython`, `m2w64` from `defaults` and `conda-forge`. I just don't know what. One time it failed to install some `msvc2015...` package and after that was installed it worked again, but not sure if that is the problem with the current setup.

**Comment by beckermr** [comment]
Closing since we are trying again in another PR.

**Pull request closed without merging**
