### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by Juanlu001**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Juanlu001** [comment]
@conda-forge-admin, please rerender

**Comment by Juanlu001** [comment]
@conda-forge-admin, please rerender

**Comment by riddell-stan** [comment]
Thanks for looking at this. I was just about to try fixing things on my branch #12 . Feel free to close that if this one fixes things.

**Comment by Juanlu001** [comment]
Hi @riddell-stan, I was just scratching my own itch :) I'm not a maintainer of this recipe but it seems that this PR did the trick, so someone please merge it so we can also bring fbprophet to Python 3.7 :)

**Comment by riddell-stan** [comment]
@rmax could this be merged? It looks good to me.

**Pull request merged**
