### PR TITLE
Update version to 2.17.0.0

### PR DESCRIPTION
**Pull request by ariddell**

### CODE REVIEW

**Comment by rmax** [comment]
The patch (that disables quadmath library) requires a sync with the latest version.

**Comment by ariddell** [comment]
I think I understand.

Out of curiosity, why is the flag BOOST_MATH_DISABLE_FLOAT128 needed with conda but not in general? I don't think anyone has mentioned it on the pystan repo.

**Comment by rmax** [comment]
> Out of curiosity, why is the flag BOOST_MATH_DISABLE_FLOAT128 needed with conda but not in general? I don't think anyone has mentioned it on the pystan repo.

@ariddell Yes. We were not able to compile the package without the patch. It may be good if you can try to build the packages without the patch.

**Comment by ariddell** [comment]
@rmax what sort of build system is being used? I'd be happy to try fixing the problem in pystan itself.

**Comment by rmax** [comment]
@ariddell the build system provided by conda and conda-forge. However, I did a test build on the CIs and the patch is no longer needed. Could you remove the patch file and the corresponding section from the recipe?

**Comment by ariddell** [comment]
Great to hear. I'll do this shortly.

**Comment by ahartikainen** [comment]
osx  build never finished? So it is still 2.16.0?

**Comment by rmax** [comment]
@ahartikainen The master build still on the queue https://travis-ci.org/conda-forge/pystan-feedstock/builds/288818645?utm_source=github_status&utm_medium=notification

OSX builds are always slow due to travis work load.

**Comment by ahartikainen** [comment]
Great! It's nice to be wrong 👍 😁

**Pull request merged**
